let


    // 현재 파일 경로를 가져오는 부분
    SourceFolder = Excel.CurrentWorkbook(){[Name="Path"]}[Content]{0}[Column1],
   
    // 상대 경로를 통해 CSV 파일 경로 설정
    SourceFile = SourceFolder & "\adobe_raw\New_Weekly_B2B_트래픽_Ken -P4 WEB - Korea.csv",
    
    // CSV 파일 불러오기
    원본 = Csv.Document(File.Contents(SourceFile), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),


//    원본 = Csv.Document(File.Contents("C:\Users\PTK\OneDrive - Cheil\바탕 화면\Weekly Report\new_report_ver2\adobe_raw\New_Weekly_B2B_트래픽_Ken -P4 WEB - Korea.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"형식 변경" = Table.TransformColumnTypes(원본,{{"Column1", type text}, {"Column2", type text}}),
    #"필터링된 행" = Table.SelectRows(#"형식 변경", each ([Column2] <> "" and [Column2] <> "Visits") and ([Column1] <> "Week")),
    #"변경된 유형" = Table.TransformColumnTypes(#"필터링된 행",{{"Column1", type datetime}, {"Column2", Int64.Type}}),
    #"추가된 사용자 지정 항목" = Table.AddColumn(#"변경된 유형", "WeekNumber", each let
    OriginalDate = [Column1],
    AddedDate = Date.AddDays(OriginalDate, 6),
    Year = if Date.Year(OriginalDate) > Date.Year(AddedDate) then Date.Year(OriginalDate) else Date.Year(AddedDate),
    WeekNumber = Date.WeekOfYear(OriginalDate)
in
    Text.From(Year) & "-" & Text.From(WeekNumber)),
    #"다시 정렬한 열 수" = Table.ReorderColumns(#"추가된 사용자 지정 항목",{"WeekNumber", "Column1", "Column2"}),
    #"이름을 바꾼 열 수" = Table.RenameColumns(#"다시 정렬한 열 수",{{"Column2", "Visits"}}),
    #"제거된 열 수" = Table.RemoveColumns(#"이름을 바꾼 열 수",{"Column1"})
in
    #"제거된 열 수"