let


    // 현재 파일 경로를 가져오는 부분
    SourceFolder = Excel.CurrentWorkbook(){[Name="Path"]}[Content]{0}[Column1],
   
    // 상대 경로를 통해 CSV 파일 경로 설정
    SourceFile = SourceFolder & "\adobe_raw\New_Weekly_캠페인_방문_Ken -P4 WEB - Korea.csv",
    
    // CSV 파일 불러오기
    원본 = Csv.Document(File.Contents(SourceFile), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),


//    원본 = Csv.Document(File.Contents("C:\Users\PTK\OneDrive - Cheil\바탕 화면\Weekly Report\new_report_ver2\adobe_raw\New_Weekly_캠페인_방문_Ken -P4 WEB - Korea.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"형식 변경" = Table.TransformColumnTypes(원본,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
    #"조건 열이 추가됨" = Table.AddColumn(#"형식 변경", "CampaignName", each if Text.StartsWith([Column1], "#") then [Column1] else null),
    #"바꾼 값" = Table.ReplaceValue(#"조건 열이 추가됨","##############################################",null,Replacer.ReplaceValue,{"CampaignName"}),
    #"다시 정렬한 열 수" = Table.ReorderColumns(#"바꾼 값",{"CampaignName", "Column1", "Column2", "Column3"}),
    #"제거된 상위 행 수" = Table.Skip(#"다시 정렬한 열 수",8),
    #"아래로 채우기" = Table.FillDown(#"제거된 상위 행 수",{"CampaignName"}),
    #"필터링된 행" = Table.SelectRows(#"아래로 채우기", each ([Column2] <> "" and [Column2] <> "0.0" and [Column2] <> "Entries" and [Column2] <> "Week") and ([Column1] <> "")),
    #"변경된 유형" = Table.TransformColumnTypes(#"필터링된 행",{{"Column2", type datetime}}),
    #"변경된 유형1" = Table.TransformColumnTypes(#"변경된 유형",{{"Column2", type date}, {"Column3", Int64.Type}}),
    #"추가된 사용자 지정 항목" = Table.AddColumn(#"변경된 유형1", "WeekNumber", each let
    OriginalDate = [Column2],
    AddedDate = Date.AddDays(OriginalDate, 6),
    Year = if Date.Year(OriginalDate) > Date.Year(AddedDate) then Date.Year(OriginalDate) else Date.Year(AddedDate),
    WeekNumber = Date.WeekOfYear(OriginalDate)
in
    Text.From(Year) & "-" & Text.From(WeekNumber)),
    #"다시 정렬한 열 수1" = Table.ReorderColumns(#"추가된 사용자 지정 항목",{"CampaignName", "WeekNumber", "Column1", "Column2", "Column3"}),
    #"이름을 바꾼 열 수" = Table.RenameColumns(#"다시 정렬한 열 수1",{{"Column1", "LastTouchChannel"}, {"Column3", "Entries"}}),
    #"제거된 열 수" = Table.RemoveColumns(#"이름을 바꾼 열 수",{"Column2"}),
    #"바꾼 값1" = Table.ReplaceValue(#"제거된 열 수","# ","",Replacer.ReplaceText,{"CampaignName"})
in
    #"바꾼 값1"