let


    // 현재 파일 경로를 가져오는 부분
    SourceFolder = Excel.CurrentWorkbook(){[Name="Path"]}[Content]{0}[Column1],
   
    // 상대 경로를 통해 CSV 파일 경로 설정
    SourceFile = SourceFolder & "\adobe_raw\New_Weekly_Scoreboard(Weekly)_Ken -P4 WEB - Korea.csv",
    
    // CSV 파일 불러오기
    원본 = Csv.Document(File.Contents(SourceFile), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),



//    원본 = Csv.Document(File.Contents("C:\Users\PTK\OneDrive - Cheil\바탕 화면\Weekly Report\new_report_ver2\adobe_raw\New_Weekly_Scoreboard(Weekly)_Ken -P4 WEB - Korea.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"형식 변경" = Table.TransformColumnTypes(원본,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
    #"조건 열이 추가됨" = Table.AddColumn(#"형식 변경", "사용자 지정", each if Text.StartsWith([Column1], "#") then [Column1] else null),
    #"제거된 상위 행 수" = Table.Skip(#"조건 열이 추가됨",8),
    #"바꾼 값" = Table.ReplaceValue(#"제거된 상위 행 수","##############################################",null,Replacer.ReplaceValue,{"사용자 지정"}),
    #"아래로 채우기" = Table.FillDown(#"바꾼 값",{"사용자 지정"}),
    #"필터링된 행1" = Table.SelectRows(#"아래로 채우기", each ([Column2] <> "" and [Column2] <> "Week") and ([사용자 지정] = "# weekly_visits_by_all_page_track")),
    #"제거된 열 수" = Table.RemoveColumns(#"필터링된 행1",{"사용자 지정"}),
    #"변경된 유형" = Table.TransformColumnTypes(#"제거된 열 수",{{"Column2", type datetime}}),
    #"추가된 사용자 지정 항목" = Table.AddColumn(#"변경된 유형", "WeekNumber", each let
    OriginalDate = [Column2],
    AddedDate = Date.AddDays(OriginalDate, 6),
    Year = if Date.Year(OriginalDate) > Date.Year(AddedDate) then Date.Year(OriginalDate) else Date.Year(AddedDate),
    WeekNumber = Date.WeekOfYear(OriginalDate)
in
    Text.From(Year) & "-" & Text.From(WeekNumber)),
    #"다시 정렬한 열 수" = Table.ReorderColumns(#"추가된 사용자 지정 항목",{"Column1", "Column2", "WeekNumber", "Column3"}),
    #"제거된 열 수1" = Table.RemoveColumns(#"다시 정렬한 열 수",{"Column2"}),
    #"다시 정렬한 열 수1" = Table.ReorderColumns(#"제거된 열 수1",{"WeekNumber", "Column1", "Column3"}),
    #"이름을 바꾼 열 수" = Table.RenameColumns(#"다시 정렬한 열 수1",{{"Column1", "Model Category_2depth"}, {"Column3", "Visits"}}),
    #"변경된 유형1" = Table.TransformColumnTypes(#"이름을 바꾼 열 수",{{"Visits", Int64.Type}}),
    #"중복된 열" = Table.DuplicateColumn(#"변경된 유형1", "Model Category_2depth", "Page Type"),
    #"바꾼 값1" = Table.ReplaceValue(#"중복된 열","flagship pdp","Flagship PD",Replacer.ReplaceText,{"Page Type"}),
    #"바꾼 값2" = Table.ReplaceValue(#"바꾼 값1","product category details","PCD",Replacer.ReplaceText,{"Page Type"}),
    #"바꾼 값3" = Table.ReplaceValue(#"바꾼 값2","product category detail","PCD",Replacer.ReplaceText,{"Page Type"}),
    #"바꾼 값4" = Table.ReplaceValue(#"바꾼 값3","product detail","PD",Replacer.ReplaceText,{"Page Type"}),
    #"바꾼 값5" = Table.ReplaceValue(#"바꾼 값4","product finder","PF",Replacer.ReplaceText,{"Page Type"}),
    #"다시 정렬한 열 수2" = Table.ReorderColumns(#"바꾼 값5",{"WeekNumber", "Model Category_2depth", "Page Type", "Visits"})
in
    #"다시 정렬한 열 수2"